COUNT_BORROWERS = "SELECT COUNT(*) FROM Borrowers"

COUNT_BOOKS = "SELECT COUNT(*) FROM Books"

COUNT_ACTIVE_LOANS = "SELECT COUNT(*) FROM Loans WHERE Status='Borrowed'"

COUNT_OVERDUE_LOANS = "SELECT COUNT(*) FROM Loans WHERE Status='Overdue'"